const fs = require('fs');
const path = require('path');
const fetch = require('node-fetch');

// Environment variables must be set on Netlify
const VERIFY_TOKEN = process.env.VERIFY_TOKEN;
const PAGE_ACCESS_TOKEN = process.env.PAGE_ACCESS_TOKEN;

// Path to the optimized JSON file generated by the Python script
// Make sure this file is uploaded to the same directory as this function
const RESPONSES_FILE = path.resolve(__dirname, '..', '..', 'responses_optimized.json');
let responsesData = {};

/**
 * Load the optimized responses data from the JSON file.
 * This function handles the new file structure with keyword indexing.
 */
async function loadResponses() {
    try {
        if (!fs.existsSync(RESPONSES_FILE)) {
            console.error("❌ responses_optimized.json file not found. Please ensure it's in the correct directory.");
            return;
        }

        const fileContent = fs.readFileSync(RESPONSES_FILE, 'utf-8');
        responsesData = JSON.parse(fileContent);
        
        console.log("✅ Optimized responses data loaded successfully.");
        console.log(`📊 Loaded ${Object.keys(responsesData.responses).length} Q&A pairs.`);
        console.log(`🔍 Indexed ${Object.keys(responsesData.keywords).length} keywords.`);
    } catch (error) {
        console.error("❌ Error loading optimized responses file:", error);
    }
}

// Load responses on startup
loadResponses();

/**
 * Main Webhook handler function
 */
exports.handler = async (event) => {
    // Check for required environment variables
    if (!VERIFY_TOKEN || !PAGE_ACCESS_TOKEN) {
        return {
            statusCode: 500,
            body: JSON.stringify({ error: "Missing environment variables" })
        };
    }

    try {
        // Verification for Facebook (GET request)
        if (event.httpMethod === "GET") {
            const params = event.queryStringParameters || {};
            if (params["hub.verify_token"] === VERIFY_TOKEN && params["hub.challenge"]) {
                console.log("✅ Webhook verified successfully.");
                return {
                    statusCode: 200,
                    body: params["hub.challenge"],
                };
            }
            return {
                statusCode: 403,
                body: "Forbidden - Invalid verify token"
            };
        }

        // Handle incoming messages (POST request)
        if (event.httpMethod === "POST") {
            if (!event.body) {
                return { statusCode: 400, body: "No body provided" };
            }

            const body = JSON.parse(event.body);

            if (body.object === "page" && body.entry) {
                await processWebhookEvents(body.entry);
                return { statusCode: 200, body: "EVENT_RECEIVED" };
            }
            return { statusCode: 404, body: "Not Found" };
        }

        return { statusCode: 405, body: "Method Not Allowed" };
    } catch (error) {
        console.error("❌ General Webhook error:", error);
        return {
            statusCode: 500,
            body: JSON.stringify({ error: "Internal server error" })
        };
    }
};

/**
 * Process webhook events from Facebook
 */
async function processWebhookEvents(entries) {
    for (const entry of entries) {
        if (entry.messaging) {
            for (const webhookEvent of entry.messaging) {
                await handleMessagingEvent(webhookEvent);
            }
        }
    }
}

/**
 * Handle a single messaging event using the optimized data
 */
async function handleMessagingEvent(webhookEvent) {
    const senderId = webhookEvent.sender?.id;

    if (!senderId) {
        console.error("❌ No sender ID found.");
        return;
    }

    try {
        if (webhookEvent.message?.text) {
            const userMsg = webhookEvent.message.text.trim().toLowerCase();
            console.log("📩 User message:", userMsg);
            
            // Search for the best response using keyword matching from the optimized data
            let botResponse = "عذراً، لم أجد إجابة لهذا السؤال. حاول صياغة السؤال بشكل مختلف.";
            let bestMatch = { score: 0, key: null };

            // Tokenize the user message and get a list of keywords
            const userKeywords = userMsg.split(/\s+/).filter(word => word.length > 2);

            // Find all potential matching questions based on keywords
            let potentialMatches = new Set();
            for (const keyword of userKeywords) {
                if (responsesData.keywords[keyword]) {
                    responsesData.keywords[keyword].forEach(key => potentialMatches.add(key));
                }
            }
            
            // Score each potential match
            for (const matchKey of potentialMatches) {
                const question = responsesData.responses[matchKey].question;
                let score = 0;
                userKeywords.forEach(userWord => {
                    if (question.includes(userWord)) {
                        score += 1;
                    }
                });
                
                // Add bonus for longer questions (more specific)
                score += question.split(/\s+/).length * 0.1;

                if (score > bestMatch.score) {
                    bestMatch = { score, key: matchKey };
                }
            }

            if (bestMatch.key) {
                botResponse = responsesData.responses[bestMatch.key].answer;
            }
            
            await sendMessage(senderId, botResponse);
        } else if (webhookEvent.postback?.payload === "GET_STARTED_PAYLOAD") {
            const welcomeText = "مرحباً بك! أنا مساعدك الذكي. اسألني عن أي شيء.";
            await sendMessage(senderId, welcomeText);
        }
    } catch (error) {
        console.error("❌ Error processing event:", error);
        await sendMessage(senderId, "عذراً، حدث خطأ. حاول مرة أخرى.");
    }
}

/**
 * Send a message back to the user
 */
async function sendMessage(recipientId, messageText) {
    const url = `https://graph.facebook.com/v19.0/me/messages?access_token=${PAGE_ACCESS_TOKEN}`;
    const payload = {
        recipient: { id: recipientId },
        message: { text: messageText }
    };

    try {
        const response = await fetch(url, {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(payload),
        });

        if (response.ok) {
            console.log("✅ Message sent successfully.");
        } else {
            const errorData = await response.text();
            console.error("❌ Failed to send message:", response.status, errorData);
        }
    } catch (error) {
        console.error("❌ Error sending message:", error);
    }
}
