[build]
  functions = "netlify/functions"
  command = "python qa_generator_arrays.py && echo 'Running Python script to generate responses file...'"
  publish = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["./responses_optimized.json"]
